from typing import List, TypedDict


class GraphState(TypedDict):
    """
    Represents the state of our graph.
    Represents the memory of our agent.

    Attributes:
        question: The user's original question
        generation: The current answer generated by the LLM
        documents: A list of documents (from Pinecone or Tavily)
        web_search: "Yes" or "No" binary flag to trigger search
        user_id: Needed to filter Pinecone
    """
    question: str
    generation: str
    documents: List[str]
    web_search: str
    user_id: str
    generation_loop_count: int  # Track retries
